main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutMe/', views.aboutMe, name="aboutMe"),
    path('myJourney/', views.myJourney, name="myJourney"),
    path('contact/', views.contact, name="contact"),
    path('myHobbies/', views.myHobbies, name="myHobbies"),
    path('viewMataKuliah/', views.viewMataKuliah, name="viewMataKuliah"),
    path('detailMataKuliah/<int:pk>/', views.detailMatkul, name="detailMatkul"),
    path('removeMataKuliah/', views.removeMataKuliah, name="removeMataKuliah"),
    path('removeMataKuliah/<int:pk>/', views.removeMatkul, name="removeMatkul"),
    path('addMataKuliah/', views.addMataKuliah, name="addMataKuliah"),
]

shafiraprofile/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story6/', include(('story6.urls', 'story6'), namespace='story6')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('story8/', include(('story8.urls', 'story8'), namespace='story8')),
    path('story9/', include(('story9.urls', 'story9'), namespace='story9'))
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.search, name='search'),
    path('keyword/', views.keyword, name='keyword')
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up/', views.signUp, name='signUp'),
    path('log-in/', views.logIn, name='logIn'),
    path('log-out/', views.logOut, name='logOut'),

]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
        }

story9/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import JsonResponse
from .forms import SignUpForm

import requests, json


# Create your views here.
def index(request):
    responds = {}
    return render(request, 'story9/index.html', responds)

def signUp(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/story9/')

    signUpForm = SignUpForm()
    if request.method == "POST":
        signUpForm = SignUpForm(request.POST)
        if signUpForm.is_valid() :
            signUpForm.save()
            messages.success(request, "Akun berhasil dibuat. Silahkan login untuk masuk ke akunmu.")
            return HttpResponseRedirect('/story9/log-in')

    responds = {'form' : signUpForm}
    return render(request, 'story9/signUp.html', responds)

def logIn(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/story9/') 

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/story9/')
        else:
            messages.info(request, "Username atau password salah")

    responds = {}
    return render(request, 'story9/logIn.html', responds)

def logOut(request):
    logout(request)
    return HttpResponseRedirect('/story9/')

story9/templates/story9/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% if user.is_authenticated %}
  <title>Welcome {{ user.get_username }}</title>
{% else %}
  <title>Welcome Page</title>
{% endif %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/story9_styles.css' %}">
{% endblock meta %}

{% block header %}
    <header class="w-100">
        <nav class="navbar navbar-inverse navbar-expand-sm font-weight-bolder mb-0">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'main:home' %}">Shafira Profile</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'story9:index' %}">Home</a></li>
                    <li><a href="{% url 'story8:search' %}">Search Book</a></li>
                </ul>

                {% if user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto">
                    <li>
                      <i class="fa fa-user-circle"></i> Halo, {{ user.get_username }}
                    </li>
                    <li><a href="{% url 'story9:logOut' %}">
                        <i class="fa fa-sign-out"></i> Logout
                    </a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav ml-auto">
                    <li><a href="{% url 'story9:signUp' %}">
                        <i class="fa fa-user-circle"></i> Sign Up
                    </a></li>
                    <li><a href="{% url 'story9:logIn' %}">
                        <i class="fa fa-sign-in"></i> Login
                    </a></li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>
{% endblock header %}

{% block content %}
<div class="container-fluid" id="main-content">
    {% if user.is_authenticated %}
    
    <h1 class="font-weight-bolder mb-5">Welcome {{ user.get_username | capfirst }}</h1>
    <div class="content">
        <p>Halo. Selamat datang, {{ user.get_username }}.</p>
        <p>Salam kenal.  Selamat bersenang-senang di website ini.</p>
    </div>
    {% else %}
    <h1 class="font-weight-bolder mb-5">Welcome</h1>
    <div class="content">
        <p>Halo. Selamat datang di website ini.</p>
        <p>Yuk masuk ke akunmu agar aku bisa menyapamu.</p>
    </div>
    {% endif %}
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/story9_scripts.js' %}"></script>
{% endblock scripts %}

story9/templates/story9/logIn.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log In</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9_styles.css' %}">
{% endblock meta %}

{% block header %}
    <header class="w-100">
        <nav class="navbar navbar-inverse navbar-expand-sm font-weight-bolder mb-0">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'main:home' %}">Shafira Profile</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'story9:index' %}">Home</a></li>
                    <li><a href="{% url 'story8:search' %}">Search Book</a></li>
                </ul>

                {% if user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <i class="fa fa-user-circle"></i> Halo, {{ user.get_username }}
                    </li>
                    <li><a href="{% url 'story9:logOut' %}">
                        <i class="fa fa-sign-out"></i> Logout
                    </a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav ml-auto">
                    <li><a href="{% url 'story9:signUp' %}">
                        <i class="fa fa-user-circle"></i> Sign Up
                    </a></li>
                    <li class="active"><a href="{% url 'story9:logIn' %}">
                        <i class="fa fa-sign-in"></i> Login
                    </a></li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>
{% endblock header %}

{% block content %}
<div class="container-fluid" id="main-content">

    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">Log In</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn login_btn" type="submit" value="Log In">
                           </div>
                </form>
            </div>
            <div>
                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor %}
            </div>
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'story9:signUp' %}" class="ml-2">Sign Up</a>
                </div>
        
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/story9_scripts.js' %}"></script>
{% endblock scripts %}

story9/templates/story9/signUp.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign Up</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9_styles.css' %}">
{% endblock meta %}

{% block header %}
    <header class="w-100">
        <nav class="navbar navbar-inverse navbar-expand-sm font-weight-bolder mb-0">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'main:home' %}">Shafira Profile</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'story9:index' %}">Home</a></li>
                    <li><a href="{% url 'story8:search' %}">Search Book</a></li>
                </ul>

                {% if user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <i class="fa fa-user-circle"></i> Halo, {{ user.get_username }}
                    </li>
                    <li><a href="{% url 'story9:logOut' %}">
                        <i class="fa fa-sign-out"></i> Logout
                    </a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav ml-auto">
                    <li class="active"><a href="{% url 'story9:signUp' %}">
                        <i class="fa fa-user-circle"></i> Sign Up
                    </a></li>
                    <li><a href="{% url 'story9:logIn' %}">
                        <i class="fa fa-sign-in"></i> Login
                    </a></li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>
{% endblock header %}

{% block content %}
<div class="container-fluid" id="main-content">

    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">Sign Up</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>

                       <div class="d-flex justify-content-center mt-3 login_container">
                         <input class="btn login_btn" type="submit" value="Sign Up">
                       </div>
                </form>
            </div>

            <div>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <p id="messages">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </div>
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'story9:logIn' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div> 
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/story9_scripts.js' %}"></script>
{% endblock scripts %}