main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutMe/', views.aboutMe, name="aboutMe"),
    path('myJourney/', views.myJourney, name="myJourney"),
    path('contact/', views.contact, name="contact"),
    path('myHobbies/', views.myHobbies, name="myHobbies"),
    path('viewMataKuliah/', views.viewMataKuliah, name="viewMataKuliah"),
    path('detailMataKuliah/<int:pk>/', views.detailMatkul, name="detailMatkul"),
    path('removeMataKuliah/', views.removeMataKuliah, name="removeMataKuliah"),
    path('removeMataKuliah/<int:pk>/', views.removeMatkul, name="removeMatkul"),
    path('addMataKuliah/', views.addMataKuliah, name="addMataKuliah"),
]

shafiraprofile/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story6/', include(('story6.urls', 'story6'), namespace='story6')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('story8/', include(('story8.urls', 'story8'), namespace='story8')),
    path('story9/', include(('story9.urls', 'story9'), namespace='story9'))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.viewKegiatan, name='viewKegiatan'),
    path('addKegiatan/', views.addKegiatan, name='addKegiatan'),
    # path('addPeserta/<int:pk>/', views.addPeserta, name='addPeserta'),
]

story6/models.py
from django.db import models

# Create your models here.
class Peserta(models.Model):
    nama = models.CharField(max_length=50, default='')
    umur = models.IntegerField(default='')

    def __str__(self):
        return self.nama

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.nama_kegiatan

story6/forms.py
from django.forms import ModelForm
from django import forms

from .models import Kegiatan, Peserta

class PesertaForm(ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'
        exclude = ['kegiatan']
        
        labels = {
            'nama': 'Nama Peserta', 
            'umur': 'Umur'
        }

        widgets = {
            'nama': forms.TextInput({'class':'form-control'}),
            'umur': forms.NumberInput({'class':'form-control'})
        }

class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        exclude = ['peserta']
        
        labels = {
            'nama_kegiatan': 'Nama Kegiatan'
        }

        widgets = {
            'nama_kegiatan': forms.TextInput({'class':'form-control'})
        }

    

story6/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Peserta, Kegiatan
from .forms import PesertaForm, KegiatanForm

def viewKegiatan(request):
    konteks = {
        'daftarKegiatan' : Kegiatan.objects.all()
    }
    return render(request, 'story6/viewKegiatan.html', konteks)

def addKegiatan(request):
    konteks = {
            'form': KegiatanForm()
        }
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/story6/')
    return render(request, 'story6/addKegiatan.html', konteks)

def addPeserta(request, pk):
    konteks = {
            'form': PesertaForm()
        }
    if request.method == 'POST':
        form = PesertaForm(request.POST)
        if form.is_valid():
            kegiatan = Kegiatan.objects.get(id=pk)
            Peserta.objects.create(nama=request.POST['nama'], kegiatan=kegiatan)
            return HttpResponseRedirect('/story6/')
    return render(request, 'story6/addPeserta.html', konteks)

story6/templates/story6/addKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Kegiatan</title>
{% endblock meta %}


{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder">Tambah Kegiatan</h1>
    <div>
        <a class="btn" href="{% url 'story6:viewKegiatan' %}">Kembali</a>
    </div>

    <div class="content ">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn-default btn">Save</button>
        </form>
    </div>

</div>

{% endblock content %}

story6/templates/story6/addPeserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Peserta</title>
{% endblock meta %}


{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder">Tambah Peserta</h1>
    <div>
        <a class="btn" href="{% url 'story6:viewKegiatan' %}">Kembali</a>
    </div>

    <div class="content ">
        <form method="POST"">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-default btn">Save</button>
        </form>
    </div>
</div>

{% endblock content %}

story6/templates/story6/viewKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profile Shafira</title>
{% endblock meta %}


{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder">Daftar Kegiatan</h1>
    <div>
        <a class="btn" href="{% url 'story6:addKegiatan' %}">Tambah Kegiatan</a>
        <a class="btn" href="{% url 'story6:addPeserta' %}">Tambah Peserta</a>
    </div>

    <div class="content">
        <div class="row row-cols-1 row-cols-lg-3">
            {% if daftarKegiatan %}
            {% for kegiatan in daftarKegiatan %}
            <div class="col mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title font-weight-bolder">{{kegiatan.nama_kegiatan}}</h5>
                        <p class="card-text">Peserta:</p>
                    </div>
                    <div class="card-footer">
                        <!-- <a class="btn" href="{% url 'story6:addPeserta' kegiatan.id %}">Tambah Peserta Kegiatan</a> -->
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}