main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutMe/', views.aboutMe, name="aboutMe"),
    path('myJourney/', views.myJourney, name="myJourney"),
    path('contact/', views.contact, name="contact"),
    path('myHobbies/', views.myHobbies, name="myHobbies"),
    path('viewMataKuliah/', views.viewMataKuliah, name="viewMataKuliah"),
    path('detailMataKuliah/<int:pk>/', views.detailMatkul, name="detailMatkul"),
    path('removeMataKuliah/', views.removeMataKuliah, name="removeMataKuliah"),
    path('removeMataKuliah/<int:pk>/', views.removeMatkul, name="removeMatkul"),
    path('addMataKuliah/', views.addMataKuliah, name="addMataKuliah"),
]

shafiraprofile/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story6/', include(('story6.urls', 'story6'), namespace='story6')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('story8/', include(('story8.urls', 'story8'), namespace='story8')),
    path('story9/', include(('story9.urls', 'story9'), namespace='story9'))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.viewKegiatan, name='viewKegiatan'),
    path('addKegiatan/', views.addKegiatan, name='addKegiatan'),
    # path('addPeserta/<int:pk>/', views.addPeserta, name='addPeserta'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.profile, name='profile')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <div class="d-flex align-items-end flex-column bd-highlight min-vh-100" id="page">

        {% block header %}
        <header class="w-100">
        <nav class="navbar p-0 navbar-expand-sm font-weight-bolder text-center text-lg-left">
            <div class="navbar-collapse">
                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
            </div>
    
            <div class="navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item pl-2 pl-md-5 my-auto">
                        <a class="nav-link" href="{% url 'story1:home' %}">Profile</a>
                    </li>
                    <li class="nav-item pl-2 pl-md-5 my-auto">
                        <a class="nav-link" href="{% url 'main:aboutMe' %}">About Me</a>
                    </li>
                    <li class="nav-item pl-2 pl-md-5 my-auto">
                        <a class="nav-link" href="{% url 'main:myJourney' %}">My Journey</a>
                    </li>
                    <li class="nav-item pl-2 pl-md-5 my-auto">
                        <a class="nav-link" href="{% url 'main:viewMataKuliah' %}">Mata Kuliah</a>
                    </li>
                    <li class="nav-item pl-2 pl-md-5 my-auto">
                        <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                    </li>
                    <!-- <li class="nav-item pl-2 pl-md-5">
                        <a class="nav-link" href="{% url 'story6:viewKegiatan' %}">Kegiatan</a>
                    </li> -->
                    <li class="nav-item pl-2 pl-md-5">
                        <a class="nav-link" href="{% url 'story7:profile' %}">Story 7</a>
                    </li>
                </ul>
            </div>
        </nav>
        </header>
        {% endblock header %}

        {% block content %}
        {% endblock content %}

        <footer class="mt-auto container-fluid p-4">
            <p class="text-center font-weight-bolder">&copy; 2020 Shafira Putri Novia Hartanti</p>
        </footer>

    </div>

    {% block scripts %}
    {% endblock scripts%}

</body>
  
</html>