main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutMe/', views.aboutMe, name="aboutMe"),
    path('myJourney/', views.myJourney, name="myJourney"),
    path('contact/', views.contact, name="contact"),
    path('myHobbies/', views.myHobbies, name="myHobbies"),
    path('viewMataKuliah/', views.viewMataKuliah, name="viewMataKuliah"),
    path('detailMataKuliah/<int:pk>/', views.detailMatkul, name="detailMatkul"),
    path('removeMataKuliah/', views.removeMataKuliah, name="removeMataKuliah"),
    path('removeMataKuliah/<int:pk>/', views.removeMatkul, name="removeMatkul"),
    path('addMataKuliah/', views.addMataKuliah, name="addMataKuliah"),
]

shafiraprofile/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story6/', include(('story6.urls', 'story6'), namespace='story6')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('story8/', include(('story8.urls', 'story8'), namespace='story8')),
    path('story9/', include(('story9.urls', 'story9'), namespace='story9'))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.viewKegiatan, name='viewKegiatan'),
    path('addKegiatan/', views.addKegiatan, name='addKegiatan'),
    # path('addPeserta/<int:pk>/', views.addPeserta, name='addPeserta'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.profile, name='profile')
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.search, name='search'),
    path('keyword/', views.keyword, name='keyword')
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up/', views.signUp, name='signUp'),
    path('log-in/', views.logIn, name='logIn'),
    path('log-out/', views.logOut, name='logOut'),

]

main/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    nama_matkul = models.CharField(max_length=50, default='')
    dosen_pengajar = models.CharField(max_length=50, default='')
    jumlah_sks = models.IntegerField(default='')
    deskripsi = models.TextField(default='')
    semester = models.CharField(max_length=20, default='')
    ruang_kelas = models.CharField(max_length=25, default='')

    def __str__(self):
        return self.nama_matkul

main/forms.py
from django.forms import ModelForm
from django import forms

from .models import MataKuliah

class MatkulForm(ModelForm):
    """ nama_matkul = forms.CharField(label='Nama mata kuliah', max_length=50)
    jumlah_sks = forms.IntegerField(label='Jumlah SKS')
    deskripsi = forms.CharField(label='Deskripsi', max_length=100)
    semester = forms.CharField(label='Semester', max_length=15)
    ruang_kelas = forms.CharField(label='Ruang kelas', max_length=20) """
    class Meta:
        model = MataKuliah
        fields = '__all__'
        
        labels = {
            'nama_matkul': 'Nama mata kuliah', 
            'dosen_pengajar': 'Dosen pengajar',
            'jumlah_sks': 'Jumlah SKS', 
            'deskripsi': 'Deskripsi', 
            'semester': 'Semester', 
            'ruang_kelas': 'Ruang Kelas'
        }

        widgets = {
            'nama_matkul': forms.TextInput({'class':'form-control'}),
            'dosen_pengajar': forms.TextInput({'class':'form-control'}),
            'jumlah_sks': forms.NumberInput({'class':'form-control'}), 
            'deskripsi': forms.TextInput({'class':'form-control'}), 
            'semester': forms.TextInput({'class':'form-control'}), 
            'ruang_kelas': forms.TextInput({'class':'form-control'})
        }

main/views.py
from django.shortcuts import render, HttpResponseRedirect

from .models import MataKuliah
from .forms import MatkulForm

def home(request):
    return render(request, 'main/home.html')

def aboutMe(request):
    return render(request, 'main/aboutMe.html')

def myJourney(request):
    return render(request, 'main/myJourney.html')

def contact(request):
    return render(request, 'main/contact.html')

def myHobbies(request):
    return render(request, 'main/myHobbies.html')

def viewMataKuliah(request):
    konteks = {
        'daftarMataKuliah' : MataKuliah.objects.all()
        }
    html = 'main/viewMataKuliah.html'
    return render(request, html, konteks)

def detailMatkul(request, pk):
    matkul = MataKuliah.objects.get(id = pk)
    konteks = {
        'mataKuliah' : matkul
        }
    html = 'main/detailMataKuliah.html'
    return render(request, html, konteks)

def addMataKuliah(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/viewMataKuliah/')
    else:
        form = MatkulForm()

    return render(request, 'main/addMataKuliah.html', {'form': form})

def removeMataKuliah(request):
    konteks = {
        'daftarMataKuliah' : MataKuliah.objects.all()
        }
    html = 'main/removeMataKuliah.html'
    return render(request, html, konteks)

def removeMatkul(request, pk):
    matkul = MataKuliah.objects.filter(id = pk)
    matkul.delete()

    return HttpResponseRedirect('/viewMataKuliah/')

main/templates/main/aboutMe.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>About Shafira</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
  <h1 class="font-weight-bolder" id="title-page">ABOUT ME</h1>
  <div class="content row">
      <div class="col-md-4 my-auto">
          <img class="mw-100" src="{% static 'img/my-photo.jpg' %}">
      </div>
      <div class="col-md-8 my-auto pt-5 pt-md-0 pl-md-5 text-center text-md-left" id="description">
          <p>Halo semuanya!<br>
              Perkenalkan nama saya Shafira Putri Novia Hartanti. Kalian bisa panggil saya Shafira. Saya merupakan seorang mahasiswa jurusan Ilmu Komputer di Universitas Indonesia. 
              Saya bertempat tinggal di di Jakarta, tepatnya di daerah Cempaka Putih. Saya memiliki hobi menonton film, khususnya yang bergenre action, komedi ataupun keduanya.
              Saya juga hobi mendengarkan musik dan membaca buku. Mau tahu lebih banyak tentang hobi saya? 
              <a href="{% url 'main:myHobbies' %}">Klik di sini</a>. 
          </p>
      </div>
  </div>
</div>
{% endblock content %}

main/templates/main/addMataKuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">ADD MATA KULIAH</h1>
    <div>
        <a class="btn" href="{% url 'main:viewMataKuliah' %}">Kembali</a>
    </div>

    <div class="content ">
        <form method="POST"">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn-default btn">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Contact</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder text-center" id="title-page">CONTACT ME</h1>
    <div class="content justify-content-center d-flex">
        <ul id="socmed-list">
            <li class="d-flex align-items-center">
                <a href="mailto:shafiraputri1001@gmail.com">
                    <img class="socmed-logo mr-4 mr-md-5" src="{% static 'img/email-logo.png' %}">
                </a>
                <a href="mailto:shafiraputri1001@gmail.com">
                    shafiraputri1001@gmail.com
                </a>
            </li>
            <li class="d-flex align-items-center">
                <a href="https://www.instagram.com/shafiranv" target="_blank">
                    <img class="socmed-logo mr-4 mr-md-5" src="{% static 'img/instagram-logo.png' %}">
                </a>
                <a href="https://www.instagram.com/shafiranv" target="_blank">
                    shafiranv
                </a>
            </li>
            <li class="d-flex align-items-center">
                <a href="https://www.linkedin.com/in/shafira-putri-n-h" target="_blank">
                    <img class="socmed-logo mr-4 mr-md-5" src="{% static 'img/linkedin-logo.png' %}">
                </a>
                <a href="https://www.linkedin.com/in/shafira-putri-n-h" target="_blank">
                    Shafira Putri Novia Hartanti
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="mx-auto">
    Icons made by <a href=https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> 
    from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
</div>
{% endblock content %}

main/templates/main/detailMataKuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">DETAIL MATA KULIAH</h1>
    <div>
        <a class="btn" href="{% url 'main:viewMataKuliah' %}">Kembali</a>
    </div>
    
    <div class="content" id ="detail-matkul">
        <h3 class="font-weight-bolder border-b"> {{ mataKuliah.nama_matkul }} </h3>
        <p class="label">Dosen Pengajar</p>
        <p>{{ mataKuliah.dosen_pengajar }}</p>
        <p class="label">Jumlah SKS</p>
        <p>{{ mataKuliah.jumlah_sks }}</p>
        <p class="label">Deskripsi</p>
        <p>{{ mataKuliah.deskripsi }}</p>
        <p class="label">Semester</p>
        <p>{{ mataKuliah.semester }}</p>
        <p class="label">Ruang Kelas</p>
        <p>{{ mataKuliah.ruang_kelas }}</p>
    </div>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Get To Know Shafira</title>
<style>
    #page {
        background: url('/static/img/jumbotron-background.jpg') center center fixed;
        background-size: auto 100vh;
        color:  #F50000;
    }
</style>
{% endblock meta %}

{% block header%}
<header class="w-100">
    <nav class="navbar p-0 navbar-expand-sm font-weight-bolder justify-content-center text-center text-lg-left">
        <ul class="navbar-nav">
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'story1:home' %}">Profile</a>
            </li>
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'main:aboutMe' %}">About Me</a>
            </li>
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'main:viewMataKuliah' %}">Mata Kuliah</a>
            </li>
            <!-- <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'story6:viewKegiatan' %}">Kegiatan</a>
            </li> -->
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'story7:profile' %}">Story 7</a>
            </li>
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'story8:search' %}">Story 8</a>
            </li> 
            <li class="nav-item pl-2 pl-md-5">
                <a class="nav-link" href="{% url 'story9:index' %}">Story 9</a>
            </li> 
        </ul>
    </nav>
</header>
{% endblock header%}

{% block content %}
<div class="container-fluid my-auto" id="homepage">
    <div class="container-fluid text-center  min-vh-90 p-5">
        <h1 class="font-weight-bolder display-3">Hello,</h1>
        <h1 class="font-weight-bolder display-3">I'm Shafira</h1>
        <p>Welcome to my website!</p>
        <a class="btn" href="{% url 'main:aboutMe' %}">Get to know me here</a>
    </div>
    
    <div class="text-center pr-3 pb-3 credits">
        Image by Susanne Jutzeler from Pexels
    </div>
</div>
{% endblock content %}

main/templates/main/myHobbies.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Shafira's Hobbies</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">MY HOBBIES</h1>
    <div class="content ">
        <div class="row row-cols-1 row-cols-lg-3">
            <div class="col mb-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title font-weight-bolder">Membaca Buku</h5>
                  <p class="card-text">Saya suka membaca buku novel. Novel yang sering saya baca biasanya bergenre <i>romance</i> atau <i>mystery</i>. Beberapa penulis novel kesukaan saya adalah Lexie Xu dan Luna Torashyngu.</p>
                </div>
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title font-weight-bolder">Menonton Film</h5>
                  <p class="card-text">Saya sangat suka menonton film, terutama film yang bergenre <i>action</i>, komedi, ataupun keduanya. </p>
                </div>
              </div>
            </div>
            <div class="col mb-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title font-weight-bolder">Mendengarkan Musik</h5>
                  <p class="card-text">Ketika saya sedang bosan dengan sesuatu, saya sering mendengarkan musik. Mendengarkan musik dapat membuat mood saya meningkat dan saya menjadi lebih bersemangat. Salah satu grup favorit saya adalah Day6.</p>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/myJourney.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Shafira's Journey</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">MY JOURNEY</h1>
    <div class="row content">
        <div class="col-md text-center text-md-right border-md-right-1 pt-4 pr-md-5">
            <h2 class="font-weight-bolder">Education</h2>
            <ul class="my-journey">
                <li>
                    <span>2016 - 2019</span><br><span class="font-weight-bolder">SMA Negeri 68 Jakarta</span>
                </li>
                <li>
                    <span>2019 - Sekarang</span><br><span class="font-weight-bolder">Universitas Indonesia</span>
                </li>
            </ul>
        </div>
        <div class="col-md text-center text-md-left border-md-left-1 pt-4 pl-md-5">
            <h2 class="font-weight-bolder">Personal Experience</h2>
            <ul class="my-journey">
                <li>
                    <span>2020 - Sekarang</span><br><span class="font-weight-bolder">Staff Humas FUKI 2020</span>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/removeMataKuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">REMOVE MATA KULIAH</h1>
    <div>
        <a class="btn" href="{% url 'main:viewMataKuliah' %}">Kembali</a>
    </div>

    <div class="content ">
        <ul>
            {% for mataKuliah in daftarMataKuliah %}
            <li>
                <a href="{% url 'main:detailMatkul' mataKuliah.id %}">{{ mataKuliah.nama_matkul }}</a>
                <a href="{% url 'main:removeMatkul' mataKuliah.id %}" class="btn btn-primary">Hapus</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

main/templates/main/viewMataKuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid" id="main-content">
    <h1 class="font-weight-bolder" id="title-page">LIST MATA KULIAH</h1>
    <div>
        <a class="btn" href="{% url 'main:addMataKuliah' %}">Tambah Mata Kuliah</a>
        <a class="btn" href="{% url 'main:removeMataKuliah' %}">Hapus Mata Kuliah</a>
    </div>

    <div class="content ">
        {% if daftarMataKuliah %}
        <ul>
            {% for mataKuliah in daftarMataKuliah %}
            <li class="mb-3"> <a href="{% url 'main:detailMatkul' mataKuliah.id %}">{{ mataKuliah.nama_matkul }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Tidak ada mata kuliah yang diambil.</p>
        {% endif %}
    </div>
</div>
{% endblock content %}